# Generated by Django 4.2.9 on 2024-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("order", models.AutoField(primary_key=True, serialize=False)),
                ("board_id", models.CharField(max_length=255)),
                ("post_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
    ]
